# This script creates app.py
with open('app.py', 'w', encoding='utf-8') as f:
    f.write('import streamlit as st\n')
    f.write('import pandas as pd\n')
    f.write('import plotly.express as px\n')
    f.write('import requests\n')
    f.write('from datetime import datetime\n')
    f.write('import time\n')
    f.write('\n')
    f.write('st.set_page_config(\n')
    f.write('    page_title="Smart WMS Dashboard",\n')
    f.write('    page_icon="🏭",\n')
    f.write('    layout="wide"\n')
    f.write(')\n')
    f.write('\n')
    f.write('st.title("🏭 Smart Warehouse Management System")\n')
    f.write('st.caption("Real-time Inventory Tracking with RFID")\n')
    f.write('\n')
    f.write('API_URL = "http://localhost:8000"\n')
    f.write('\n')
    f.write('with st.sidebar:\n')
    f.write('    st.header("Controls")\n')
    f.write('    auto_refresh = st.checkbox("Auto-refresh", value=True)\n')
    f.write('    refresh_rate = st.slider("Refresh rate (seconds)", 5, 60, 10)\n')
    f.write('    \n')
    f.write('    if st.button("🔄 Refresh Now"):\n')
    f.write('        st.cache_data.clear()\n')
    f.write('        st.rerun()\n')
    f.write('    \n')
    f.write('    st.divider()\n')
    f.write('    st.caption(f"Last updated: {datetime.now().strftime(\'%H:%M:%S\')}")\n')
    f.write('\n')
    f.write('@st.cache_data(ttl=10)\n')
    f.write('def fetch_inventory():\n')
    f.write('    try:\n')
    f.write('        response = requests.get(f"{API_URL}/api/inventory/levels", timeout=5)\n')
    f.write('        if response.status_code == 200:\n')
    f.write('            return response.json()\n')
    f.write('    except:\n')
    f.write('        return None\n')
    f.write('    return None\n')
    f.write('\n')
    f.write('@st.cache_data(ttl=10)\n')
    f.write('def fetch_alerts():\n')
    f.write('    try:\n')
    f.write('        response = requests.get(f"{API_URL}/api/inventory/alerts", timeout=5)\n')
    f.write('        if response.status_code == 200:\n')
    f.write('            return response.json()\n')
    f.write('    except:\n')
    f.write('        return None\n')
    f.write('    return None\n')
    f.write('\n')
    f.write('@st.cache_data(ttl=10)\n')
    f.write('def fetch_scans():\n')
    f.write('    try:\n')
    f.write('        response = requests.get(f"{API_URL}/api/scans/recent?limit=20", timeout=5)\n')
    f.write('        if response.status_code == 200:\n')
    f.write('            return response.json()\n')
    f.write('    except:\n')
    f.write('        return None\n')
    f.write('    return None\n')
    f.write('\n')
    f.write('@st.cache_data\n')
    f.write('def get_demo_data():\n')
    f.write('    return pd.DataFrame({\n')
    f.write('        "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],\n')
    f.write('        "SKU": ["LAP001", "MOU001", "KEY001", "MON001"],\n')
    f.write('        "Current Stock": [2, 2, 1, 1],\n')
    f.write('        "Reorder Point": [3, 5, 4, 2],\n')
    f.write('        "Status": ["Low Stock", "Low Stock", "Low Stock", "Low Stock"]\n')
    f.write('    })\n')
    f.write('\n')
    f.write('col1, col2, col3, col4 = st.columns(4)\n')
    f.write('\n')
    f.write('inventory_data = fetch_inventory()\n')
    f.write('\n')
    f.write('if inventory_data:\n')
    f.write('    df = pd.DataFrame(inventory_data)\n')
    f.write('    st.success("✅ Connected to backend API")\n')
    f.write('else:\n')
    f.write('    df = get_demo_data()\n')
    f.write('    st.warning("⚠️ Using demo data - Backend not connected")\n')
    f.write('\n')
    f.write('if not df.empty:\n')
    f.write('    with col1:\n')
    f.write('        st.metric("Total Products", len(df))\n')
    f.write('    with col2:\n')
    f.write('        total = df["Current Stock"].sum() if "Current Stock" in df.columns else df["current_quantity"].sum()\n')
    f.write('        st.metric("Total Items", int(total))\n')
    f.write('    with col3:\n')
    f.write('        if "Status" in df.columns:\n')
    f.write('            low = len(df[df["Status"] == "Low Stock"])\n')
    f.write('        else:\n')
    f.write('            low = len(df[df["needs_reorder"] == True])\n')
    f.write('        st.metric("Low Stock Alerts", low)\n')
    f.write('    with col4:\n')
    f.write('        scan_count = len(fetch_scans()) if fetch_scans() else 12\n')
    f.write('        st.metric("Recent Scans", scan_count)\n')
    f.write('\n')
    f.write('col_left, col_right = st.columns([2, 1])\n')
    f.write('\n')
    f.write('with col_left:\n')
    f.write('    st.subheader("📊 Inventory Levels")\n')
    f.write('    \n')
    f.write('    x_col = "Product" if "Product" in df.columns else "name"\n')
    f.write('    y_col = "Current Stock" if "Current Stock" in df.columns else "current_quantity"\n')
    f.write('    color_col = "Status" if "Status" in df.columns else "needs_reorder"\n')
    f.write('    \n')
    f.write('    fig = px.bar(\n')
    f.write('        df,\n')
    f.write('        x=x_col,\n')
    f.write('        y=y_col,\n')
    f.write('        color=color_col,\n')
    f.write('        title="Current Stock Levels",\n')
    f.write('        color_discrete_map={"Low Stock": "red", "Healthy": "green", True: "red", False: "green"}\n')
    f.write('    )\n')
    f.write('    st.plotly_chart(fig, use_container_width=True)\n')
    f.write('\n')
    f.write('with col_right:\n')
    f.write('    st.subheader("⚠️ Low Stock Alerts")\n')
    f.write('    \n')
    f.write('    alerts = fetch_alerts()\n')
    f.write('    if alerts:\n')
    f.write('        for alert in alerts[:5]:\n')
    f.write('            st.warning(f"**{alert.get(\'product_name\', \'Unknown\')}**  \\nStock: {alert.get(\'current_quantity\', 0)} units")\n')
    f.write('    else:\n')
    f.write('        for product in ["Laptop", "Mouse", "Keyboard", "Monitor"]:\n')
    f.write('            st.warning(f"**{product}**  \\nStock: Low - Reorder needed")\n')
    f.write('\n')
    f.write('st.subheader("📋 Recent Scans")\n')
    f.write('scans = fetch_scans()\n')
    f.write('if scans:\n')
    f.write('    scan_df = pd.DataFrame(scans[:10])\n')
    f.write('    st.dataframe(scan_df, use_container_width=True)\n')
    f.write('else:\n')
    f.write('    demo_scans = pd.DataFrame({\n')
    f.write('        "RFID Tag": ["RFID001", "RFID002", "RFID003", "RFID004"],\n')
    f.write('        "Location": ["Loading Dock", "Shipping Bay", "Quality Check", "Packing Area"],\n')
    f.write('        "Time": ["2 min ago", "15 min ago", "1 hour ago", "2 hours ago"]\n')
    f.write('    })\n')
    f.write('    st.dataframe(demo_scans, use_container_width=True)\n')
    f.write('\n')
    f.write('if auto_refresh:\n')
    f.write('    time.sleep(refresh_rate)\n')
    f.write('    st.rerun()\n')
    f.write('\n')
    f.write('st.divider()\n')
    f.write('st.caption(f"Smart WMS v1.0 | Running on Streamlit Cloud | {datetime.now().strftime(\'%Y-%m-%d %H:%M:%S\')}")\n')

print("create_app.py fixed!")
